### ISSUE TITLE
获取月份最后一天 return new Date(date.getFullYear(), date.getMonth() + 1, 0);不明白

### ISSUE THREAD

**Issue by Zouxiaoqing** [smltq/jPublic#12]
/**
     * 获取月份最后一天
     * @param {Date}    date    日期(默认当前日期)
     * @returns {Date}
     * @alias module:_.lastDay
     * @example
     * _.dateFormat(_.lastDay());
     * =>2019-05-31 00:00:00
     */
    _.lastDay = function (date) {
        date || (date = new Date());
        return new Date(date.getFullYear(), date.getMonth() + 1, 0);
    };

这里的new date 是用当前日期和时间创建新的日期对象。为何date.getMonth() + 1，比如date.getMonth() 是11，加了1后，为什么显示出来的时候不会变成12

**Comment by Zouxiaoqing** [comment]
2、此函数有bug。月份为2的时候不通过。

**Comment by Zouxiaoqing** [comment]
![image](https://user-images.githubusercontent.com/50507613/58937071-f5840600-87a3-11e9-93c8-eb85b996816d.png)

**Comment by smltq** [comment]
assert.ok(_.dateFormat(_.lastDay(new Date('2019-2-3 06:20:30'))) == '2019-02-28 00:00:00','2019年2月的最后一天是2019-2-28');
这样测试用例能通过。
