### ISSUE TITLE
数组差集，结果未带上数组符号

### ISSUE THREAD

**Issue by Zouxiaoqing** [smltq/jPublic#13]
![image](https://user-images.githubusercontent.com/50507613/58942301-16eaef00-87b0-11e9-9330-0a61bf50b08c.png)
 如_.difference([1,2,3],[1,2])，实际结果为3，期望结果应该为[3]

**Comment by smltq** [comment]
返回结果为[3]，但是数组不能用==比较，建议使用_.equals对比数组是否相等
