### ISSUE TITLE
返回日期的yyyy-MM-dd格式函数是否有误？

### ISSUE THREAD

**Issue by Zouxiaoqing** [smltq/jPublic#14]
测试用例如下
 QUnit.test('返回日期的yyyy-MM-dd格式:_.shortDateFormat',function(assert){
        assert.ok(_.shortDateFormat(new Date('2016,4,5,17,55,55')),'2016,4,5,17,55,55的简洁日期为'+_.shortDateFormat(2016,4,5,17,55,55));
    });

测试结果为：
![image](https://user-images.githubusercontent.com/50507613/59010617-73a7e180-8864-11e9-9284-337e01d35cf5.png)

**Comment by Zouxiaoqing** [comment]
![image](https://user-images.githubusercontent.com/50507613/59010654-9803be00-8864-11e9-89f4-082ab9708b3f.png)

**Comment by smltq** [comment]
2016,4,5,17,55,55这个日期格式不对，无法识别，会返回最小日期

**Comment by DHclly** [comment]
> 2016,4,5,17,55,55这个日期格式不对，无法识别，会返回最小日期

日期格式不对应该抛出异常，而不是返回最小值

**Comment by smltq** [comment]
> > 2016,4,5,17,55,55这个日期格式不对，无法识别，会返回最小日期
> 
> 日期格式不对应该抛出异常，而不是返回最小值

增加_.isValidDate函数，并的dateFormat函数里增加参数类型验证
