### ISSUE TITLE
_.formatTime函数没有判断取值范围

### ISSUE THREAD

**Issue by Zouxiaoqing** [smltq/jPublic#15]
![image](https://user-images.githubusercontent.com/50507613/59170928-53816680-8b73-11e9-984e-9a708f8d8fcc.png)
![image](https://user-images.githubusercontent.com/50507613/59170939-5bd9a180-8b73-11e9-976e-f61e67c9c54d.png)

**Comment by smltq** [comment]
formatTime增加负数限制
